version: "3.8"
services:
  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  #fluent-bit:
  #  build: ./fluent-bit
  #  container_name: fluent-bit
  #  volumes:
  #   - /var/log:/var/log


