apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      timeField: "@timestamp"
      esVersion: 7
      interval: "1s"
      logMessageField: "log"
      logLevelField: "level"
    isDefault: true
